CREATE DATABASE racket;

USE racket;

CREATE table bhaskara (
    a INTEGER NOT NULL,
    b INTEGER NOT NULL,
    c INTEGER NOT NULL,
    delta DOUBLE(100,30) NOT NULL,
    x1 DOUBLE(100,30) NOT NULL,
    x2 DOUBLE(100,30) NOT NULL,
    Vx DOUBLE(100,30) NOT NULL,
    Vy DOUBLE(100,30) NOT NULL
);